project:
  type: website
  output-dir: docs

website:
  title: "Riley (Jiarui) Li"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: About
      - text: Resume
        href: resume.qmd
      - href: projects.qmd
        text: Projects
      - text: Blog
        href: blog.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
