<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Riley Li">
<meta name="dcterms.date" content="2026-06-06">
<meta name="description" content="A comprehensive simulation study using Python to explore the statistical foundations of A/B testing, covering the Law of Large Numbers, Central Limit Theorem, and the risks of data peeking.">

<title>A/B Testing a Call to Action – Riley (Jiarui) Li</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-3bd9fd8f8e76ce670d657f77156ae519.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Riley (Jiarui) Li</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-ab-test-as-a-statistical-problem" id="toc-the-ab-test-as-a-statistical-problem" class="nav-link" data-scroll-target="#the-ab-test-as-a-statistical-problem">The A/B Test as a Statistical Problem</a></li>
  <li><a href="#simulating-data" id="toc-simulating-data" class="nav-link" data-scroll-target="#simulating-data">Simulating Data</a></li>
  <li><a href="#the-law-of-large-numbers" id="toc-the-law-of-large-numbers" class="nav-link" data-scroll-target="#the-law-of-large-numbers">The Law of Large Numbers</a></li>
  <li><a href="#bootstrap-standard-errors" id="toc-bootstrap-standard-errors" class="nav-link" data-scroll-target="#bootstrap-standard-errors">Bootstrap Standard Errors</a></li>
  <li><a href="#the-central-limit-theorem" id="toc-the-central-limit-theorem" class="nav-link" data-scroll-target="#the-central-limit-theorem">The Central Limit Theorem</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis Testing</a></li>
  <li><a href="#the-t-test-as-a-regression" id="toc-the-t-test-as-a-regression" class="nav-link" data-scroll-target="#the-t-test-as-a-regression">The T-Test as a Regression</a></li>
  <li><a href="#the-problem-with-peeking" id="toc-the-problem-with-peeking" class="nav-link" data-scroll-target="#the-problem-with-peeking">The Problem with Peeking</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A/B Testing a Call to Action</h1>
<p class="subtitle lead">Simulating Key Ideas from Classical Frequentist Statistics</p>
</div>

<div>
  <div class="description">
    A comprehensive simulation study using Python to explore the statistical foundations of A/B testing, covering the Law of Large Numbers, Central Limit Theorem, and the risks of data peeking.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Riley Li </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 6, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Every website with a newsletter faces the same quiet question: which words actually convince people to sign up? On a homepage, the phrasing of a single button or headline — the “call to action” (CTA) — can meaningfully change how many visitors become subscribers. To answer this question rigorously, we run an <strong>A/B test</strong>.</p>
<p>The setup is simple. We have two candidate CTAs:</p>
<ul>
<li><strong>CTA A:</strong> “Sign up for our newsletter here!”</li>
<li><strong>CTA B:</strong> “Stay up to date by signing up!”</li>
</ul>
<p>Each visitor to our site is randomly assigned to see one of the two options. We then compare the sign-up rates between the two groups. Random assignment is the key ingredient: it ensures that any difference in outcomes is attributable to the CTA itself, not to the type of person who happened to see it.</p>
<p>In this post, we work through the statistical machinery behind such a test using simulated data. Along the way, we visit some of the most important ideas in classical frequentist statistics: the Law of Large Numbers, the bootstrap, the Central Limit Theorem, hypothesis testing, and the connection between a t-test and linear regression. We also demonstrate a subtle but serious pitfall — what happens when an impatient analyst peeks at the results too early.</p>
</section>
<section id="the-ab-test-as-a-statistical-problem" class="level2">
<h2 class="anchored" data-anchor-id="the-ab-test-as-a-statistical-problem">The A/B Test as a Statistical Problem</h2>
<p>Each visitor either signs up or does not, making their outcome a binary 0/1 variable. We model this as a draw from a <strong>Bernoulli distribution</strong>: a coin flip with some probability <span class="math inline">\(\pi\)</span> of landing heads (signing up).</p>
<p>Because the CTA a visitor sees might influence their decision, we allow the sign-up probability to differ by group:</p>
<ul>
<li>Visitors who see CTA A sign up with probability <span class="math inline">\(\pi_A\)</span></li>
<li>Visitors who see CTA B sign up with probability <span class="math inline">\(\pi_B\)</span></li>
</ul>
<p>The quantity we actually care about is the <strong>difference in sign-up rates</strong>: <span class="math display">\[\theta = \pi_A - \pi_B\]</span></p>
<p>If <span class="math inline">\(\theta &gt; 0\)</span>, CTA A performs better. If <span class="math inline">\(\theta &lt; 0\)</span>, CTA B wins. If <span class="math inline">\(\theta = 0\)</span>, it doesn’t matter which one we use.</p>
<p>Of course, we don’t observe <span class="math inline">\(\pi_A\)</span> and <span class="math inline">\(\pi_B\)</span> directly — we only observe the outcomes for the visitors in our experiment. Our best guess at <span class="math inline">\(\theta\)</span> is the <strong>difference in sample proportions</strong>: <span class="math display">\[\hat\theta = \bar{X}_A - \bar{X}_B\]</span></p>
<p>Since each observation is 0 or 1, the sample mean is just the fraction who signed up, so <span class="math inline">\(\bar{X}_A = \hat\pi_A\)</span> and <span class="math inline">\(\bar{X}_B = \hat\pi_B\)</span>. This is our estimator. The rest of this post is about understanding its behavior.</p>
</section>
<section id="simulating-data" class="level2">
<h2 class="anchored" data-anchor-id="simulating-data">Simulating Data</h2>
<p>In a real experiment we would not know the true values of <span class="math inline">\(\pi_A\)</span> and <span class="math inline">\(\pi_B\)</span> — that is the whole point of running the test. But for the purposes of this exercise, we set the true values ourselves. This lets us study how our estimator behaves when we know exactly what the right answer is.</p>
<p>We set <span class="math inline">\(\pi_A = 0.22\)</span> and <span class="math inline">\(\pi_B = 0.18\)</span>, so the true difference is <span class="math inline">\(\theta = 0.04\)</span>. We then simulate 1,000 Bernoulli draws for each group — as if 2,000 visitors arrived at our site, half randomly assigned to each CTA.</p>
<div id="cf6756ac" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pi_A <span class="op">=</span> <span class="fl">0.22</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pi_B <span class="op">=</span> <span class="fl">0.18</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>theta_true <span class="op">=</span> pi_A <span class="op">-</span> pi_B</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>data_A <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, pi_A, n)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>data_B <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, pi_B, n)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>pi_hat_A <span class="op">=</span> data_A.mean()</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>pi_hat_B <span class="op">=</span> data_B.mean()</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>theta_hat <span class="op">=</span> pi_hat_A <span class="op">-</span> pi_hat_B</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Estimated sign-up rate, CTA A: </span><span class="sc">{</span>pi_hat_A<span class="sc">:.3f}</span><span class="ss">  (true: </span><span class="sc">{</span>pi_A<span class="sc">}</span><span class="ss">)"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Estimated sign-up rate, CTA B: </span><span class="sc">{</span>pi_hat_B<span class="sc">:.3f}</span><span class="ss">  (true: </span><span class="sc">{</span>pi_B<span class="sc">}</span><span class="ss">)"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Estimated difference θ̂:        </span><span class="sc">{</span>theta_hat<span class="sc">:.3f}</span><span class="ss">  (true: </span><span class="sc">{</span>theta_true<span class="sc">}</span><span class="ss">)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated sign-up rate, CTA A: 0.216  (true: 0.22)
Estimated sign-up rate, CTA B: 0.178  (true: 0.18)
Estimated difference θ̂:        0.038  (true: 0.04000000000000001)</code></pre>
</div>
</div>
<p>Our estimates land close to the truth, but not exactly — that small gap is just random sampling noise. The rest of this post is about quantifying and reasoning about that noise.</p>
</section>
<section id="the-law-of-large-numbers" class="level2">
<h2 class="anchored" data-anchor-id="the-law-of-large-numbers">The Law of Large Numbers</h2>
<p>The <strong>Law of Large Numbers</strong> (LLN) tells us that as the sample size grows, the sample mean converges to the population mean. Applied to our problem: as more visitors accumulate in each group, <span class="math inline">\(\hat\pi_A\)</span> will get closer and closer to <span class="math inline">\(\pi_A\)</span>, and therefore <span class="math inline">\(\hat\theta\)</span> will get closer and closer to the true <span class="math inline">\(\theta = 0.04\)</span>. This is what gives us confidence in our estimator in the first place — given enough data, it will eventually find the right answer.</p>
<p>We can demonstrate this visually. For each observation <span class="math inline">\(i = 1, 2, \ldots, 1000\)</span>, we compute the element-wise difference between the CTA A and CTA B draws, then track the running mean of those differences as <span class="math inline">\(i\)</span> grows.</p>
<div id="2d16c1f6" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>diffs <span class="op">=</span> data_A <span class="op">-</span> data_B</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>cumulative_avg <span class="op">=</span> np.cumsum(diffs) <span class="op">/</span> np.arange(<span class="dv">1</span>, n <span class="op">+</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="6a2e0849" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-5-output-1.png" width="951" height="420" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>With just a handful of observations, the running mean swings wildly — anywhere from well below zero to well above 0.10. But as the sample size grows, the estimate settles down and homes in on the true value of 0.04. By 1,000 observations it has converged to 0.038, just a hair below the truth. The LLN is what justifies collecting more data when we are uncertain: patience is eventually rewarded with accuracy.</p>
</section>
<section id="bootstrap-standard-errors" class="level2">
<h2 class="anchored" data-anchor-id="bootstrap-standard-errors">Bootstrap Standard Errors</h2>
<p>The LLN tells us our estimator will eventually be right. But with a fixed sample — say, 1,000 visitors per group — how precise is it? We need more than a point estimate; we need a <strong>confidence interval</strong> that communicates our uncertainty.</p>
<p>One way to get there is the <strong>bootstrap</strong>. The idea is elegant: instead of deriving a formula for the variability of <span class="math inline">\(\hat\theta\)</span>, we let the data speak for themselves. We treat our observed sample as a stand-in for the population, and repeatedly resample from it (with replacement) to simulate what would happen if we ran the experiment many times. The spread of the resulting estimates tells us how variable <span class="math inline">\(\hat\theta\)</span> is.</p>
<div id="09155e1f" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>n_boot <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>boot_thetas <span class="op">=</span> np.zeros(n_boot)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_boot):</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    resample_A <span class="op">=</span> np.random.choice(data_A, size<span class="op">=</span>n, replace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    resample_B <span class="op">=</span> np.random.choice(data_B, size<span class="op">=</span>n, replace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    boot_thetas[i] <span class="op">=</span> resample_A.mean() <span class="op">-</span> resample_B.mean()</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>se_boot <span class="op">=</span> boot_thetas.std()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We compare the bootstrapped standard error to the closed-form analytical formula. For the difference in means of two independent Bernoulli samples: <span class="math display">\[SE(\hat\theta) = \sqrt{\frac{\hat\pi_A(1 - \hat\pi_A)}{n_A} + \frac{\hat\pi_B(1 - \hat\pi_B)}{n_B}}\]</span></p>
<div id="b63a7c30" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>se_analytical <span class="op">=</span> np.sqrt(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    pi_hat_A <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> pi_hat_A) <span class="op">/</span> n <span class="op">+</span> pi_hat_B <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> pi_hat_B) <span class="op">/</span> n</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>ci_lower <span class="op">=</span> theta_hat <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> se_boot</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>ci_upper <span class="op">=</span> theta_hat <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> se_boot</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> [</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"Point estimate θ̂"</span>,  <span class="ss">f"</span><span class="sc">{</span>theta_hat<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"Bootstrap SE"</span>,       <span class="ss">f"</span><span class="sc">{</span>se_boot<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"Analytical SE"</span>,      <span class="ss">f"</span><span class="sc">{</span>se_analytical<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"95% CI lower"</span>,       <span class="ss">f"</span><span class="sc">{</span>ci_lower<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"95% CI upper"</span>,       <span class="ss">f"</span><span class="sc">{</span>ci_upper<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>Markdown(tabulate(results, headers<span class="op">=</span>[<span class="st">"Quantity"</span>, <span class="st">"Value"</span>], tablefmt<span class="op">=</span><span class="st">"pipe"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="6">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Point estimate θ̂</td>
<td style="text-align: right;">0.038</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bootstrap SE</td>
<td style="text-align: right;">0.0177</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Analytical SE</td>
<td style="text-align: right;">0.0178</td>
</tr>
<tr class="even">
<td style="text-align: left;">95% CI lower</td>
<td style="text-align: right;">0.0034</td>
</tr>
<tr class="odd">
<td style="text-align: left;">95% CI upper</td>
<td style="text-align: right;">0.0726</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The bootstrap SE (0.0177) and the analytical SE (0.0178) are nearly identical — reassuring evidence that the bootstrap is working correctly. Using the bootstrap SE, our 95% confidence interval for <span class="math inline">\(\theta\)</span> is roughly <strong>[0.003, 0.073]</strong>. The interval is entirely above zero, suggesting CTA A has a higher sign-up rate, though the true difference could be anywhere from negligibly small to about 7 percentage points.</p>
<div id="ddea391a" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-8-output-1.png" width="855" height="370" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-central-limit-theorem" class="level2">
<h2 class="anchored" data-anchor-id="the-central-limit-theorem">The Central Limit Theorem</h2>
<p>We now understand that <span class="math inline">\(\hat\theta\)</span> will converge to the truth (LLN) and that we can estimate its variability (bootstrap). But to do formal hypothesis testing, we need to know the <em>shape</em> of <span class="math inline">\(\hat\theta\)</span>’s sampling distribution — not just its mean and spread.</p>
<p>The <strong>Central Limit Theorem</strong> (CLT) provides the answer: regardless of the shape of the underlying population distribution, the sampling distribution of the sample mean becomes approximately <strong>Normal</strong> as the sample size grows. Since <span class="math inline">\(\hat\theta\)</span> is a difference of two sample means, the same applies here.</p>
<p>We demonstrate this by repeating the experiment 1,000 times for each of four sample sizes <span class="math inline">\(n \in \{25, 50, 100, 500\}\)</span> and plotting the distribution of the resulting <span class="math inline">\(\hat\theta\)</span> values.</p>
<div id="b2a00e14" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-9-output-1.png" width="1141" height="776" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>At <span class="math inline">\(n = 25\)</span>, the histogram is ragged and noticeably asymmetric — there just are not enough observations to smooth out the lumpy underlying Bernoulli distribution. By <span class="math inline">\(n = 100\)</span> the distribution already looks quite bell-shaped, and by <span class="math inline">\(n = 500\)</span> it is nearly indistinguishable from a Normal curve. This progression is the CLT in action. For our experiment with <span class="math inline">\(n = 1000\)</span> per group, we can be confident that <span class="math inline">\(\hat\theta\)</span> is well-approximated by a Normal distribution, which is the foundation for the hypothesis test in the next section.</p>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h2>
<p>We now have all the ingredients for a formal test. We want to evaluate whether the observed difference between the two CTAs is large enough to rule out pure chance.</p>
<p>We set up two competing hypotheses:</p>
<ul>
<li><strong>Null hypothesis</strong> <span class="math inline">\(H_0: \theta = 0\)</span> — the two CTAs produce the same sign-up rate</li>
<li><strong>Alternative hypothesis</strong> <span class="math inline">\(H_1: \theta \neq 0\)</span> — the CTAs differ</li>
</ul>
<p>The CLT tells us that <span class="math inline">\(\hat\theta\)</span> is approximately Normal in large samples. Under <span class="math inline">\(H_0\)</span>, the mean of that distribution is 0. To figure out how extreme our observed <span class="math inline">\(\hat\theta\)</span> is, we standardize it: <span class="math display">\[z = \frac{\hat\theta - 0}{SE(\hat\theta)}\]</span></p>
<p>This works for three reasons. First, by the CLT, <span class="math inline">\(\hat\theta\)</span> is approximately Normal. Second, under <span class="math inline">\(H_0\)</span>, it is centered at zero. Third, dividing a Normal random variable by its standard deviation produces a standard Normal <span class="math inline">\(N(0,1)\)</span>. So <span class="math inline">\(z \;\dot\sim\; N(0,1)\)</span> under the null, and we know exactly how big <span class="math inline">\(z\)</span> would need to be to be considered surprising.</p>
<p>This procedure is sometimes called a <strong>t-test</strong>, but that label is slightly imprecise in our setting. A true t-distribution arises when the underlying data are Normal <em>and</em> the variance is unknown — the ratio of the estimate to its estimated SE then follows an exact t-distribution. Here, our data are Bernoulli (not Normal), so there is no exact result; we rely on the CLT for approximate Normality. What we are doing is closer to a <strong>z-test</strong>. For large samples the t-distribution and the standard Normal are nearly identical, so the distinction has no practical consequence — but it matters conceptually.</p>
<div id="a2d6b2af" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>z_stat <span class="op">=</span> theta_hat <span class="op">/</span> se_analytical</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> stats.norm.cdf(<span class="bu">abs</span>(z_stat)))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> [</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"θ̂"</span>,                   <span class="ss">f"</span><span class="sc">{</span>theta_hat<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"SE"</span>,                   <span class="ss">f"</span><span class="sc">{</span>se_analytical<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"z-statistic"</span>,          <span class="ss">f"</span><span class="sc">{</span>z_stat<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"p-value (two-sided)"</span>,  <span class="ss">f"</span><span class="sc">{</span>p_value<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>Markdown(tabulate(summary, headers<span class="op">=</span>[<span class="st">"Quantity"</span>, <span class="st">"Value"</span>], tablefmt<span class="op">=</span><span class="st">"pipe"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="9">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">θ̂</td>
<td style="text-align: right;">0.038</td>
</tr>
<tr class="even">
<td style="text-align: left;">SE</td>
<td style="text-align: right;">0.0178</td>
</tr>
<tr class="odd">
<td style="text-align: left;">z-statistic</td>
<td style="text-align: right;">2.1388</td>
</tr>
<tr class="even">
<td style="text-align: left;">p-value (two-sided)</td>
<td style="text-align: right;">0.0325</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The z-statistic is 2.14, and the two-sided p-value is 0.032. Since 0.032 &lt; 0.05, we reject the null hypothesis at the 5% significance level. Our data provide statistically significant evidence that CTA A and CTA B produce different sign-up rates.</p>
<p>Interpreting this carefully: the p-value does not say there is a 3.2% chance the null is true. It says that <em>if</em> the null were true, we would observe a difference this large or larger only 3.2% of the time by chance alone. We judged that unlikely enough to reject <span class="math inline">\(H_0\)</span>.</p>
<p>To make this concrete, the figure below shows the standard normal sampling distribution of the z-statistic under <span class="math inline">\(H_0\)</span>. The shaded red regions are the rejection zones at the 5% significance level (anything beyond <span class="math inline">\(|z| &gt; 1.96\)</span>). Our observed <span class="math inline">\(z = 2.14\)</span> lands inside the right-hand rejection zone, and the orange tails together represent the two-sided p-value of 0.032: the probability of seeing a result this extreme or more, if the null were true.</p>
<div id="d5c87f43" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-11-output-1.png" width="951" height="421" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The visual makes the test outcome unambiguous: the observed <span class="math inline">\(z\)</span> falls beyond the critical value, so we reject <span class="math inline">\(H_0\)</span>. It also shows why peeking, which we examine in the final section, is so dangerous: every additional check is another chance for random noise to push <span class="math inline">\(z\)</span> into the red zone purely by accident.</p>
</section>
<section id="the-t-test-as-a-regression" class="level2">
<h2 class="anchored" data-anchor-id="the-t-test-as-a-regression">The T-Test as a Regression</h2>
<p>The two-sample test above is mathematically equivalent to a simple linear regression — a connection that is easy to miss but surprisingly useful. Understanding it opens the door to a much more flexible framework for analyzing experiments.</p>
<p>The setup: we stack the CTA A and CTA B observations into a single dataset with an outcome <span class="math inline">\(Y_i\)</span> (1 = signed up, 0 = did not) and a treatment indicator <span class="math inline">\(D_i\)</span> (1 = saw CTA A, 0 = saw CTA B). We then fit: <span class="math display">\[Y_i = \beta_0 + \beta_1 D_i + \varepsilon_i\]</span></p>
<p>The coefficients have clean interpretations:</p>
<ol type="1">
<li><span class="math inline">\(\beta_0\)</span> is the expected <span class="math inline">\(Y_i\)</span> when <span class="math inline">\(D_i = 0\)</span> — the mean of the B group, which estimates <span class="math inline">\(\pi_B\)</span></li>
<li><span class="math inline">\(\beta_0 + \beta_1\)</span> is the expected <span class="math inline">\(Y_i\)</span> when <span class="math inline">\(D_i = 1\)</span> — the mean of the A group, which estimates <span class="math inline">\(\pi_A\)</span></li>
<li>Therefore <span class="math inline">\(\beta_1 = \pi_A - \pi_B = \theta\)</span></li>
</ol>
<p>In other words, <span class="math inline">\(\hat\beta_1\)</span> is numerically identical to <span class="math inline">\(\hat\theta\)</span>.</p>
<div id="96247270" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> np.concatenate([data_A, data_B])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>D <span class="op">=</span> np.concatenate([np.ones(n), np.zeros(n)])</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>df_reg <span class="op">=</span> pd.DataFrame({<span class="st">'Y'</span>: Y, <span class="st">'D'</span>: D})</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">'Y ~ D'</span>, data<span class="op">=</span>df_reg).fit()</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>comparison <span class="op">=</span> [</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"Two-sample z-test"</span>, <span class="ss">f"</span><span class="sc">{</span>theta_hat<span class="sc">:.6f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>se_analytical<span class="sc">:.6f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>z_stat<span class="sc">:.4f}</span><span class="ss">"</span>,          <span class="ss">f"</span><span class="sc">{</span>p_value<span class="sc">:.6f}</span><span class="ss">"</span>],</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"OLS Regression"</span>,    <span class="ss">f"</span><span class="sc">{</span>model<span class="sc">.</span>params[<span class="st">'D'</span>]<span class="sc">:.6f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>model<span class="sc">.</span>bse[<span class="st">'D'</span>]<span class="sc">:.6f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>model<span class="sc">.</span>tvalues[<span class="st">'D'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>, <span class="ss">f"</span><span class="sc">{</span>model<span class="sc">.</span>pvalues[<span class="st">'D'</span>]<span class="sc">:.6f}</span><span class="ss">"</span>],</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>Markdown(tabulate(comparison,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>                  headers<span class="op">=</span>[<span class="st">"Method"</span>, <span class="st">"θ̂ / β̂₁"</span>, <span class="st">"SE"</span>, <span class="st">"Test statistic"</span>, <span class="st">"p-value"</span>],</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>                  tablefmt<span class="op">=</span><span class="st">"pipe"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="11">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 27%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 26%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: right;">θ̂ / β̂₁</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">Test statistic</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Two-sample z-test</td>
<td style="text-align: right;">0.038</td>
<td style="text-align: right;">0.017767</td>
<td style="text-align: right;">2.1388</td>
<td style="text-align: right;">0.03245</td>
</tr>
<tr class="even">
<td style="text-align: left;">OLS Regression</td>
<td style="text-align: right;">0.038</td>
<td style="text-align: right;">0.017776</td>
<td style="text-align: right;">2.1377</td>
<td style="text-align: right;">0.032658</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The point estimates and test statistics are essentially identical. The tiny difference in standard errors arises because OLS assumes a single pooled variance across groups, while our two-sample formula allows separate variances — the distinction rarely matters in practice.</p>
<p>Why does this equivalence matter? Because the regression framework generalizes naturally to more complex settings: add a control variable for the day of the week, include an interaction to test whether the CTA effect differs by device type, or extend to three or more treatment arms. In each case the same OLS machinery produces valid inference, while the mechanics of the underlying two-sample test would need to be rederived from scratch.</p>
</section>
<section id="the-problem-with-peeking" class="level2">
<h2 class="anchored" data-anchor-id="the-problem-with-peeking">The Problem with Peeking</h2>
<p>So far, everything has gone smoothly. We ran our experiment, waited for the data to come in, and conducted a single test. But in practice, patience is in short supply. What if we checked the results along the way — say, after every 100 new visitors per group — and stopped the experiment the moment one of those interim tests came back significant?</p>
<p>This practice, called <strong>peeking</strong>, is a serious problem under classical frequentist statistics. A single test at <span class="math inline">\(\alpha = 0.05\)</span> has a 5% chance of a false positive — rejecting <span class="math inline">\(H_0\)</span> even when it is true. But each additional peek is another opportunity to get unlucky. Across multiple tests on accumulating data, the probability of at least one false rejection climbs far above 5%.</p>
<p>We can demonstrate this with a simulation. We set <span class="math inline">\(\pi_A = \pi_B = 0.20\)</span> — the null is <em>true</em>, there is no difference between the CTAs — and simulate 10,000 experiments. In each experiment, we peek after every 100 observations per group (at <span class="math inline">\(n = 100, 200, \ldots, 1000\)</span>) and flag the experiment as a false positive if any of the 10 interim tests reaches <span class="math inline">\(p &lt; 0.05\)</span>.</p>
<div id="0fc25834" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>pi_null <span class="op">=</span> <span class="fl">0.20</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>n_total <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>peek_points <span class="op">=</span> np.arange(<span class="dv">100</span>, n_total <span class="op">+</span> <span class="dv">1</span>, <span class="dv">100</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>n_experiments <span class="op">=</span> <span class="dv">10_000</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>false_positive_count <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_experiments):</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    expA <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, pi_null, n_total)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    expB <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, pi_null, n_total)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> peek_n <span class="kw">in</span> peek_points:</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>        ph_A <span class="op">=</span> expA[:peek_n].mean()</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>        ph_B <span class="op">=</span> expB[:peek_n].mean()</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>        se <span class="op">=</span> np.sqrt(ph_A<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>ph_A)<span class="op">/</span>peek_n <span class="op">+</span> ph_B<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>ph_B)<span class="op">/</span>peek_n)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> se <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>        p <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> stats.norm.cdf(<span class="bu">abs</span>((ph_A <span class="op">-</span> ph_B) <span class="op">/</span> se)))</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> p <span class="op">&lt;</span> alpha:</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>            false_positive_count <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>empirical_fpr <span class="op">=</span> false_positive_count <span class="op">/</span> n_experiments</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Nominal alpha (single test):    </span><span class="sc">{</span>alpha<span class="sc">:.1%}</span><span class="ss">"</span>)</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Empirical false positive rate:  </span><span class="sc">{</span>empirical_fpr<span class="sc">:.1%}</span><span class="ss">  (</span><span class="sc">{</span>empirical_fpr<span class="op">/</span>alpha<span class="sc">:.1f}</span><span class="ss">x inflation)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nominal alpha (single test):    5.0%
Empirical false positive rate:  19.9%  (4.0x inflation)</code></pre>
</div>
</div>
<div id="edcd8196" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-14-output-1.png" width="855" height="467" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>With a single look at the data, the false positive rate is right at 5% — exactly as advertised. But with 10 interim peeks, the empirical false positive rate jumps to roughly <strong>20%</strong>, nearly four times the nominal level. The bar chart makes the inflation visible: each additional look adds more and more probability of a spurious “significant” result.</p>
<p>The lesson is stark. If you run a test and check it repeatedly until it crosses <span class="math inline">\(p &lt; 0.05\)</span>, you are not really running a 5%-level test — you are running a much more permissive one without realizing it. In practice, the remedy is to decide in advance how many observations you will collect and commit to a single final test, or to use methods specifically designed for sequential testing (such as sequential probability ratio tests or Bayesian approaches) that account for the multiple looks explicitly.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>